"""Dihedral (D4) symmetry of Costas arrays.

A Costas array is a permutation matrix whose pairwise difference vectors are all
distinct. The eight symmetries of the square grid (rotations by 0/90/180/270 and
the four reflections) each map a Costas array to a Costas array, so Costas arrays
fall into orbits of size dividing 8. Searching only the canonical (lexicographic
minimum) representative of each orbit is a sound up-to-8x reduction for both
existence search and impossibility proofs.

Permutations are 1-indexed lists: ``perm[c-1]`` is the row of the dot in column
``c``. The group is generated by:
  - reverse r:    flip columns,  g(c) = f(N+1-c)
  - complement k: flip rows,     g(c) = N+1-f(c)
  - inverse t:    transpose,     g = f^{-1}
We take the closure of these generators, which is robust to composition
bookkeeping and always yields the full group of order 8 (or a divisor, for
self-symmetric arrays).
"""
from __future__ import annotations

from typing import Iterable, Sequence


def reverse(perm: Sequence[int]) -> tuple[int, ...]:
    """Flip columns: g(c) = f(N+1-c)."""
    return tuple(perm[::-1])


def complement(perm: Sequence[int]) -> tuple[int, ...]:
    """Flip rows: g(c) = N+1-f(c)."""
    n = len(perm)
    return tuple(n + 1 - v for v in perm)


def inverse(perm: Sequence[int]) -> tuple[int, ...]:
    """Transpose: g = f^{-1} (g(r) = c iff f(c) = r)."""
    n = len(perm)
    out = [0] * n
    for c, r in enumerate(perm, start=1):
        out[r - 1] = c
    return tuple(out)


_GENERATORS = (reverse, complement, inverse)


def dihedral_orbit(perm: Sequence[int]) -> list[tuple[int, ...]]:
    """All distinct images of ``perm`` under the dihedral group (size divides 8)."""
    start = tuple(perm)
    seen = {start}
    frontier = [start]
    while frontier:
        current = frontier.pop()
        for gen in _GENERATORS:
            nxt = gen(current)
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return sorted(seen)


def is_canonical(perm: Sequence[int]) -> bool:
    """True iff ``perm`` is the lexicographic minimum of its orbit."""
    target = tuple(perm)
    return all(target <= image for image in dihedral_orbit(target))


def to_canonical(perm: Sequence[int]) -> tuple[int, ...]:
    """The lexicographic-minimum representative of ``perm``'s orbit."""
    return min(dihedral_orbit(perm))


# ---------------------------------------------------------------------------
# Grid-cell view: each transform is a fixed permutation of the N*N cells. This
# is what the SAT lex-leader symmetry-breaking encoding needs (it constrains the
# 0/1 grid variables, not the permutation directly).
# ---------------------------------------------------------------------------

def grid_cell_maps(order: int) -> dict[str, list[tuple[int, int]]]:
    """For each non-identity D4 transform, return a list `m` of length N*N such
    that the variable for cell index `j` (0-based, j = col*N + row) maps to the
    cell `m[j] = (col', row')` in the transformed array. Cells use 0-based
    (col, row). Identity is omitted."""
    n = order
    transforms = {
        "reverse": lambda c, r: (n - 1 - c, r),
        "complement": lambda c, r: (c, n - 1 - r),
        "rot180": lambda c, r: (n - 1 - c, n - 1 - r),
        "transpose": lambda c, r: (r, c),
        "antitranspose": lambda c, r: (n - 1 - r, n - 1 - c),
        "rot90": lambda c, r: (r, n - 1 - c),
        "rot270": lambda c, r: (n - 1 - r, c),
    }
    maps: dict[str, list[tuple[int, int]]] = {}
    for name, fn in transforms.items():
        cells = []
        for c in range(n):
            for r in range(n):
                cells.append(fn(c, r))
        maps[name] = cells
    return maps
